<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cld</string>
		<string>cloudformation</string>
		<string>cloud.json</string>
	</array>
	<key>name</key>
	<string>cloudformation</string>
	<key>scopeName</key>
	<string>source.cloudformation</string>
	<key>uuid</key>
	<string>B69D3BA7-5ABB-4751-83B9-C71A359CAD96</string>
</dict>
</plist>
